E2Helper.Descriptions["fin3GetAngleOfAttack(e:)"] = "Returns the angle of attack of a Fin 3 fin."
E2Helper.Descriptions["fin3SetCamber(e:n)"] = "Sets the camber of a Fin 3 fin. Good for simulating flaps and slats."
E2Helper.Descriptions["fin3GetCamber(e:)"] = "Returns the camber of a Fin 3 fin."
E2Helper.Descriptions["fin3SetBladePitch(e:n)"] = "Sets the angle of a Fin 3 propeller's blades."
E2Helper.Descriptions["fin3GetBladePitch(e:)"] = "Returns the angle of a Fin 3 propeller's blades."
E2Helper.Descriptions["fin3GetPropellerRPM(e:)"] = "Returns the RPM of a Fin 3 propeller."